version: '2.3'

services:
  db:
    image: mongo
    container_name: node_api_dev_db
    restart: always
    ports:
      - '27027:27017'
    networks:
      - node-dev-network

  web:
    container_name: node_api_dev
    hostname: node_api
    build:
      context: .
      args:
        RUN_ENVIRONMENT: docker
    restart: on-failure
    cpus: "0.4"
    mem_reservation: "120m"
    depends_on:
      - db
    links:
      - db
    ports:
      - '9000:3001'
    volumes:
      - .:/app/node_api
    networks:
      - node-dev-network
    command: ["wait-for-it", "db:27017", "--"]

networks:
  node-dev-network:
    driver: "bridge"

